// <auto-generated />
using System;
using BataSCADA.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BataSCADA.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230711164605_Alarms")]
    partial class Alarms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BataSCADA.Models.AddressValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AddressValues");
                });

            modelBuilder.Entity("BataSCADA.Models.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalogInputTagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Limit")
                        .HasColumnType("float");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Triggered")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("BataSCADA.Models.AlarmLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("bit");

                    b.Property<double>("Limit")
                        .HasColumnType("float");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AlarmLogs");
                });

            modelBuilder.Entity("BataSCADA.Models.Tag", b =>
                {
                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagName");

                    b.ToTable("Tags", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BataSCADA.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLoggedIn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BataSCADA.Models.AnalogInput", b =>
                {
                    b.HasBaseType("BataSCADA.Models.Tag");

                    b.Property<int>("Driver")
                        .HasColumnType("int");

                    b.Property<double>("HighLimit")
                        .HasColumnType("float");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<double>("LowLimit")
                        .HasColumnType("float");

                    b.Property<int>("ScanTime")
                        .HasColumnType("int");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AnalogInputs", (string)null);
                });

            modelBuilder.Entity("BataSCADA.Models.AnalogOutput", b =>
                {
                    b.HasBaseType("BataSCADA.Models.Tag");

                    b.Property<double>("HighLimit")
                        .HasColumnType("float");

                    b.Property<double>("InitialValue")
                        .HasColumnType("float");

                    b.Property<double>("LowLimit")
                        .HasColumnType("float");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.ToTable("AnalogOutputs", (string)null);
                });

            modelBuilder.Entity("BataSCADA.Models.DigitalInput", b =>
                {
                    b.HasBaseType("BataSCADA.Models.Tag");

                    b.Property<int>("Driver")
                        .HasColumnType("int");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<int>("ScanTime")
                        .HasColumnType("int");

                    b.ToTable("DigitalInputs", (string)null);
                });

            modelBuilder.Entity("BataSCADA.Models.DigitalOutput", b =>
                {
                    b.HasBaseType("BataSCADA.Models.Tag");

                    b.Property<bool>("InitialValue")
                        .HasColumnType("bit");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.ToTable("DigitalOutputs", (string)null);
                });

            modelBuilder.Entity("BataSCADA.Models.AnalogInput", b =>
                {
                    b.HasOne("BataSCADA.Models.Tag", null)
                        .WithOne()
                        .HasForeignKey("BataSCADA.Models.AnalogInput", "TagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BataSCADA.Models.AnalogOutput", b =>
                {
                    b.HasOne("BataSCADA.Models.Tag", null)
                        .WithOne()
                        .HasForeignKey("BataSCADA.Models.AnalogOutput", "TagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BataSCADA.Models.DigitalInput", b =>
                {
                    b.HasOne("BataSCADA.Models.Tag", null)
                        .WithOne()
                        .HasForeignKey("BataSCADA.Models.DigitalInput", "TagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BataSCADA.Models.DigitalOutput", b =>
                {
                    b.HasOne("BataSCADA.Models.Tag", null)
                        .WithOne()
                        .HasForeignKey("BataSCADA.Models.DigitalOutput", "TagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
